apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pelican-database
  namespace: pelican
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Create DB before pelican workload
spec:
  instances: 2

  affinity:
    nodeSelector:
      workloads/games: ""

  storage:
    size: 10Gi
    storageClass: longhorn

  bootstrap:
    initdb:
      database: panel
      owner: pelican
