apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pelican-database
  namespace: pelican
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Create DB before pelican workload
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18.6-system-trixie
  instances: 2

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: workloads/games
                operator: Exists

  storage:
    size: 10Gi
    storageClass: longhorn

  bootstrap:
    initdb:
      database: panel
      owner: pelican
