image:
  repository: ghcr.io/mia-riezebos/caelestis-backend
  tag: 0.7.0
  digest: sha256:8909c214a413358678fdb259f9461df710eab7521ce9b77283a115dc6bc86e9a
  pullPolicy: IfNotPresent
frontend:
  image:
    repository: ghcr.io/mia-riezebos/caelestis-frontend
    tag: 0.6.1
    digest: sha256:ab0cd879d8719e8686c6c9d2a77b2759254a4cde36bc61ab6fdf726302061233
    pullPolicy: IfNotPresent

server:
  name: TAC
  origin: https://tac.caelest.is
  season: 0
  basePath: /backend
  openAccess: false
  existingSecret: caelestis-server

database:
  adapter: postgres
  host: caelestis-database-rw.caelestis.svc
  existingSecret: caelestis-database-app
  tls:
    mode: verify-full
    existingSecret: caelestis-database-ca

storage:
  adapter: filesystem
persistence:
  storageClass: longhorn
  size: 20Gi

nodeSelector:
  workloads/critical: "true"
  kubernetes.io/arch: amd64
