image:
  repository: ghcr.io/mia-riezebos/caelestis-backend
  tag: 0.9.0
  digest: sha256:31e6e27935fd775caa6995b3c8393e028ddaaecd5f76114376a82e707bc74d00
  pullPolicy: IfNotPresent
frontend:
  image:
    repository: ghcr.io/mia-riezebos/caelestis-frontend
    tag: 0.7.0
    digest: sha256:f9dd2127523e2b3b93c466b3df3508d8672dd0418546acf82bf8e8f382b57b64
    pullPolicy: IfNotPresent

server:
  name: TAC
  origin: https://tac.caelest.is
  season: 0
  basePath: /backend
  openAccess: false
  existingSecret: caelestis-server

database:
  adapter: postgres
  host: caelestis-database-rw.caelestis.svc
  existingSecret: caelestis-database-app
  tls:
    mode: verify-full
    existingSecret: caelestis-database-ca

storage:
  adapter: filesystem
persistence:
  storageClass: longhorn
  size: 20Gi

nodeSelector:
  workloads/critical: "true"
  kubernetes.io/arch: amd64
