## Helm values for Lidarr on K3s
## Chart: bjw-s/app-template (v3)
## Repo: https://bjw-s-labs.github.io/helm-charts

controllers:
  main:
    pod:
      securityContext:
        fsGroup: 1000
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: workloads/media
                    operator: Exists
                  - key: workloads/downloading
                    operator: Exists
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/lidarr
          tag: 3.1.0.4875-ls27
          pullPolicy: IfNotPresent
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: Europe/Amsterdam
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 4Gi

service:
  main:
    controller: main
    ports:
      http:
        port: 8686

ingress:
  main:
    enabled: false
    hosts:
      - lidarr.yggdrasil.mia.cx

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: lidarr
    globalMounts:
      - path: /config
  media:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: media-nfs-pvc
    globalMounts:
      - path: /media
  downloads:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: nvme-nfs-pvc
    globalMounts:
      - path: /downloads
        subPath: sabnzbd
