apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "tenant.database" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18.6-system-trixie
  instances: {{ .Values.tenant.database.instances }}
  affinity:
    nodeSelector:
      workloads/critical: "true"
  storage:
    size: {{ .Values.tenant.database.size }}
    storageClass: longhorn
  bootstrap:
    initdb:
      database: caelestis
      owner: caelestis
